from pathlib import Path
from bs4 import BeautifulSoup
P=Path(__file__).resolve().parents[1]/'hvor-mye-kan-jeg-lane-bolig.html'
s=BeautifulSoup(P.read_text(encoding='utf-8'),'html.parser')
if not s.select_one('[data-borrowing-capacity-tool="v1"]'):
 sec=BeautifulSoup('''<section class="tool-card borrowing-capacity-tool" data-borrowing-capacity-tool="v1"><p class="eyebrow">LÅNERAMME-SJEKK</p><h2>Få et første estimat på lånerammen</h2><p>Se hva gjeldsgrensen og egenkapitalen kan bety før banken vurderer utgifter og betjeningsevne.</p><label>Brutto årsinntekt i husholdningen (kr)<input id="bc-income" inputmode="decimal" value="700000"></label><div class="borrowing-tool-grid"><label>Eksisterende gjeld (kr)<input id="bc-debt" inputmode="decimal" value="300000"></label><label>Egenkapital (kr)<input id="bc-equity" inputmode="decimal" value="500000"></label></div><button class="calc-action" id="bc-btn" type="button">Beregn første estimat</button><div aria-live="polite" class="tool-result" id="bc-result">Legg inn tallene dine for å se et regelbasert første estimat.</div><p class="article-note">Estimatet bruker hovedreglene om maksimal samlet gjeld på fem ganger årsinntekt og 90 prosent belåningsgrad. Det er ikke et lånetilbud. Banken må også vurdere blant annet utgifter, kreditt, sikkerhet og betjeningsevne.</p><p><a data-revenue-context="borrowing_capacity_tool_v1" data-revenue-event="problem_route" href="mangler-egenkapital-bolig.html">Er egenkapitalen flaskehalsen? Se mulige spor →</a></p><p><a class="cta" data-revenue-context="borrowing_capacity_tool_v1" data-revenue-event="commercial_route" href="sjekk/boliglan/">Undersøk boliglånsalternativer →</a></p></section>''','html.parser').section
 lead=s.select_one('.trust-box')
 lead.insert_after(sec)
 js=s.new_tag('script');js.string="""(function(){function n(id){return Number((document.getElementById(id).value||'').replace(/\\s/g,'').replace(',','.'))||0}function kr(v){return Math.max(0,Math.floor(v/1000)*1000).toLocaleString('nb-NO')+' kr'}document.getElementById('bc-btn').addEventListener('click',function(){var income=n('bc-income'),debt=n('bc-debt'),equity=n('bc-equity'),o=document.getElementById('bc-result');if(!(income>0)||debt<0||equity<0){o.textContent='Kontroller at feltene inneholder gyldige tall.';return}var debtRoom=Math.max(0,income*5-debt);var priceFromEquity=equity/0.10;var loanFromEquity=priceFromEquity-equity;var loan=Math.max(0,Math.min(debtRoom,loanFromEquity));var price=loan+equity;o.innerHTML='<strong>Omtrent '+kr(loan)+'</strong> i mulig nytt boliglån som et første regelestimat, tilsvarende boligpris rundt '+kr(price)+'. Banken kan komme til et lavere beløp etter vurdering av betjeningsevne og øvrige forhold.';});})();"""
 s.body.append(js)
 if not s.select_one('link[href="design-v44.css"]'): s.head.append(s.new_tag('link',rel='stylesheet',href='design-v44.css'))
P.write_text(str(s),encoding='utf-8')
print('Borrowing capacity tool applied')
