from pathlib import Path
from bs4 import BeautifulSoup
R=Path(__file__).resolve().parents[1];p=R/'guide-effektiv-nominell-rente.html'
s=BeautifulSoup(p.read_text(encoding='utf-8'),'html.parser')
if not s.select_one('[data-nominal-effective-tool="v1"]'):
 anchor=s.select_one('[data-rate-authority="nominal-effective-v1"]')
 sec=BeautifulSoup('''<section class="tool-card rate-cost-tool" data-nominal-effective-tool="v1"><p class="eyebrow">REGN I KRONER</p><h2>Hva betyr rente og gebyrer for lånekostnaden?</h2><p>Legg inn et eksempel og se et enkelt kostnadsestimat. Dette er ikke en beregning av bankens oppgitte effektive rente, men viser hvorfor gebyrer og rente bør vurderes sammen.</p><label>Lånebeløp (kr)<input id="ne-amount" inputmode="decimal" value="200000"/></label><label>Nominell rente (%)<input id="ne-rate" inputmode="decimal" value="8.0"/></label><label>Løpetid (år)<input id="ne-years" inputmode="decimal" value="5"/></label><label>Etableringsgebyr (kr)<input id="ne-startfee" inputmode="decimal" value="1500"/></label><label>Termingebyr per måned (kr)<input id="ne-monthfee" inputmode="decimal" value="50"/></label><button class="calc-action" id="ne-calc" type="button">Beregn kostnadsestimat</button><div aria-live="polite" class="tool-result" id="ne-result">Fyll inn tallene og beregn.</div><p class="calc-note">Forenklet annuitetsestimat. Faktisk effektiv rente og total kostnad avhenger av vilkårene i det konkrete tilbudet.</p><div class="tool-next" id="ne-next" hidden><strong>Vil du sammenligne videre?</strong><p>Bruk samme blikk på rente, gebyrer og total kostnad når du vurderer konkrete alternativer.</p><a class="cta" data-revenue-context="nominal_effective_cost_tool_v1" data-revenue-event="commercial_route" href="sjekk/boliglan/">Undersøk boliglånsalternativer →</a><a class="text-link" data-revenue-context="nominal_effective_cost_tool_v1" data-revenue-event="problem_route" href="guide-sammenligne-boliglan.html">Se hvordan lånetilbud bør sammenlignes →</a></div></section>''','html.parser').section
 anchor.insert_after(sec)
 script=s.new_tag('script');script.string="""(()=>{const n=id=>document.getElementById(id),num=id=>Number(String(n(id).value).replace(/\\s/g,'').replace(',','.'))||0,fmt=x=>Math.round(x).toLocaleString('nb-NO')+' kr';n('ne-calc')?.addEventListener('click',()=>{const P=num('ne-amount'),annual=num('ne-rate')/100,years=num('ne-years'),start=num('ne-startfee'),mf=num('ne-monthfee'),months=Math.max(1,Math.round(years*12)),r=annual/12;if(P<=0||years<=0){n('ne-result').textContent='Skriv inn lånebeløp og løpetid.';return}const payment=r>0?P*r/(1-Math.pow(1+r,-months)):P/months,total=payment*months+start+mf*months,cost=total-P;n('ne-result').innerHTML='<strong>Ca. '+fmt(payment+mf)+'/mnd</strong><span>Estimert samlet rente + gebyrer: '+fmt(cost)+' · estimert total tilbakebetaling: '+fmt(total)+'</span>';n('ne-next').hidden=false;window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'calculator_result',calculator:'nominal_effective_cost',result_class:cost>0?'cost_shown':'no_cost'});});})();"""
 sec.insert_after(script)
 if not s.select_one('link[href="design-v45.css"]'):
  link=s.new_tag('link',rel='stylesheet',href='design-v45.css');s.head.append(link)
 p.write_text(str(s),encoding='utf-8')
print('Nominal/effective cost tool applied')
